src/Entity/Chipset.php
<?php

namespace App\Entity;

use App\Entity\Traits\ImpreciseDateTrait;
use App\Repository\ChipsetRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ChipsetRepository::class)]
class Chipset
{
    use ImpreciseDateTrait;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Manufacturer::class, inversedBy: 'chipsets')]
    #[Assert\NotBlank(message: 'Manufacturer cannot be blank')]
    private $manufacturer;

    #[ORM\OneToMany(targetEntity: Motherboard::class, mappedBy: 'chipset')]
    private $motherboards;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Length(max: 255, maxMessage: 'Name is longer than {{ limit }} characters.')]
    private $name;

    #[ORM\OneToMany(targetEntity: ChipsetAlias::class, mappedBy: 'chipset', orphanRemoval: true, cascade: ['persist'])]
    #[Assert\Valid()]
    private $chipsetAliases;

    /**
     * @var ArrayCollection<Chip>
     */
    #[ORM\ManyToMany(targetEntity: Chip::class, inversedBy: 'chipsets')]
    private $chips;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Length(max: 255, maxMessage: 'Encyclopedia link is longer than {{ limit }} characters.')]
    private $encyclopedia_link;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    #[Assert\Length(max: 255, maxMessage: 'Part number is longer than {{ limit }} characters.')]
    private $part_no;

    #[ORM\OneToMany(targetEntity: ChipsetBiosCode::class, mappedBy: 'chipset', orphanRemoval: true, cascade: ['persist'])]
    #[Assert\Valid()]
    private $biosCodes;

    #[ORM\OneToMany(targetEntity: LargeFileChipset::class, mappedBy: 'chipset', orphanRemoval: true, cascade: ['persist'])]
    #[Assert\Valid()]
    private $drivers;

    #[ORM\Column(type: 'string', length: 8192, nullable: true)]
    #[Assert\Length(max: 8192, maxMessage: 'Description is longer than {{ limit }} characters.')]
    private $description;

    #[ORM\OneToMany(targetEntity: ChipsetDocumentation::class, mappedBy: 'chipset', orphanRemoval: true, cascade: ['persist'])]
    #[Assert\Valid()]
    private $documentations;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $lastEdited = null;

    #[ORM\Column(length: 255)]
    private ?string $cachedName = null;

    public function __construct()
    {
        $this->motherboards = new ArrayCollection();
        $this->chipsetAliases = new ArrayCollection();
        $this->chips = new ArrayCollection();
        $this->biosCodes = new ArrayCollection();
        $this->drivers = new ArrayCollection();
        $this->documentations = new ArrayCollection();
        $this->lastEdited = new \DateTime('now');
    }
    public function __toString(): string
    {
        return $this->getNameCached();
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getManufacturer(): ?Manufacturer
    {
        return $this->manufacturer;
    }
    public function setManufacturer(?Manufacturer $manufacturer): self
    {
        $this->manufacturer = $manufacturer;

        return $this;
    }
    public function getNameCached(): string
    {
        return $this->getFullName() . " " . $this->getPartsCached();
    }
    public function getNameCachedSearch(): string
    {
        $fullName = $this->getManufacturer()?->getName();
        if($this->getId() == null){
            if($fullName == "")
                return "Not identified";
            return "any " . $fullName . " chipset";
        }
        if ($this->part_no) {
            $fullName .= " $this->part_no";
            if ($this->name) {
                $fullName .= " ($this->name)";
            }
            $fullName .= " " . $this->getPartsCached();
        } else {
            if ($this->name) {
                $fullName .= " $this->name";
                if(strtolower($this->name) != "unidentified")
                    $fullName .= " " . $this->getPartsCached();
            } else {
                $fullName .= " unidentified";
            }
        }
        $fullName = strlen($fullName) > 80 ? substr($fullName,0,80)."..." : $fullName;
        return $fullName;
    }
    public function getFullName(): string
    {
        $fullName = $this->getManufacturer()?->getName();
        if ($this->part_no) {
            $fullName .= " $this->part_no";
            if ($this->name) {
                $fullName .= " ($this->name)";
            }
        } else {
            if ($this->name) {
                $fullName .= " $this->name";
            } else {
                $fullName .= " Unidentified";
            }
        }
        return $fullName;
    }
    public function getParts(): string
    {
        $parts = "";
        if($this->chips->isEmpty()){
            return "[no parts]";
        }
        foreach ($this->chips as $key => $part) {
            if ($key === array_key_last($this->chips->getValues())) {
                $parts .= $part->getManufacturerAndPN();
            } else {
                $parts .= $part->getManufacturerAndPN() . ", ";
            }
        }
        if ($parts) {
            $parts = "[$parts]";
        }


        return "$parts";
    }
    public function getPartsCached(): string
    {
        return ($this->getCachedName() != "") ? $this->getCachedName() : "[uncached parts]";
    }
    /**
     * @return Collection|Motherboard[]
     */
    public function getMotherboards(): Collection
    {
        return $this->motherboards;
    }
    public function addMotherboard(Motherboard $motherboard): self
    {
        if (!$this->motherboards->contains($motherboard)) {
            $this->motherboards[] = $motherboard;
            $motherboard->setChipset($this);
        }

        return $this;
    }
    public function removeMotherboard(Motherboard $motherboard): self
    {
        if ($this->motherboards->contains($motherboard)) {
            $this->motherboards->removeElement($motherboard);
            // set the owning side to null (unless already changed)
            if ($motherboard->getChipset() === $this) {
                $motherboard->setChipset(null);
            }
        }

        return $this;
    }
    public function getName(): ?string
    {
        return $this->name;
    }
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
    /**
     * @return Collection|Chip[]
     */
    public function getChips(): Collection
    {
        $sortedChips = $this->chips->toArray();

        $res = usort($sortedChips, function ($a, $b) {
            return ($a->getFullName() <=> $b->getFullName());
        });

        if ($res) {
            return new ArrayCollection($sortedChips);
        } else {
            return $this->chips;
        }
    }
    public function addChip(Chip $chip): self
    {
        if (!$this->chips->contains($chip)) {
            $this->chips[] = $chip;
            $chip->addChipset($this);
        }

        return $this;
    }
    public function removeChip(Chip $chip): self
    {
        if ($this->chips->contains($chip)) {
            $this->chips->removeElement($chip);
            // set the owning side to null (unless already changed)
            if ($chip->getChipsets()->contains($this)) {
                $chip->removeChipset($this);
            }
        }

        return $this;
    }
    public function getEncyclopediaLink(): ?string
    {
        return $this->encyclopedia_link;
    }
    public function setEncyclopediaLink(?string $encyclopedia_link): self
    {
        $this->encyclopedia_link = $encyclopedia_link;

        return $this;
    }
    public function getPartNumber(): ?string
    {
        return $this->getPartNo();
    }
    public function getNameWithoutManuf(): string
    {
        $fullName = "";
        if ($this->part_no) {
            $fullName .= "$this->part_no";
            if ($this->name) {
                $fullName .= " ($this->name)";
            }
        } else {
            if ($this->name) {
                $fullName .= "$this->name";
            } else {
                $fullName .= "Unidentified";
            }
        }
        return $fullName;
    }
    public function getPartNo(): ?string
    {
        return $this->part_no;
    }
    public function setPartNo(?string $part_no): self
    {
        $this->part_no = $part_no;

        return $this;
    }
    /**
     * @return Collection|ChipsetBiosCode[]
     */
    public function getBiosCodes(): Collection
    {
        return $this->biosCodes;
    }
    public function addBiosCode(ChipsetBiosCode $biosCode): self
    {
        if (!$this->biosCodes->contains($biosCode)) {
            $this->biosCodes[] = $biosCode;
            $biosCode->setChipset($this);
        }

        return $this;
    }
    public function removeBiosCode(ChipsetBiosCode $biosCode): self
    {
        if ($this->biosCodes->contains($biosCode)) {
            $this->biosCodes->removeElement($biosCode);
            // set the owning side to null (unless already changed)
            if ($biosCode->getChipset() === $this) {
                $biosCode->setChipset(null);
            }
        }

        return $this;
    }
    /**
     * @return Collection|LargeFileChipset[]
     */
    public function getDrivers(): Collection
    {
        return $this->drivers;
    }
    public function getAllDrivers(): Collection
    {
        $drivers = $this->drivers->toArray();
        foreach ($this->getChips() as $chip) {
            $drivers = array_merge($drivers, $chip->getDrivers()->toArray());
        }
        return new ArrayCollection($drivers);
    }
    public function addDriver(LargeFileChipset $driver): self
    {

templates/macros/aliases.html.twig
{% if entity is defined and entity is not empty %}
	<div class="textarea">
		<h3><b>{{ msg }}</b></h3>
		{% if fullSort is defined %}
			{% set sortedEntity = entity|sort((a, b) => a.name <=> b.name)|sort((a, b) => a.partNumber <=> b.partNumber) %}
		{% else %}
			{% set sortedEntity = entity|sort %}
		{% endif %}
{% apply markdown_to_html %}{% for alias in sortedEntity %}
* {{ alias.getFullAliasName() }}
{% endfor %}{% endapply %}
	</div>
{% endif %}

templates/macros/bios.html.twig
{% if entity is not empty %}
    <div class="plain-list w300p table">
        <div class="list-entry centered head">
            <div>Version</div>
            <div>Note</div>
            <div>File</div>
            <div>Logs</div>
        </div>
        {% for bios in entity|sort((a, b) => b.version <=> a.version) %}
        <div class="list-entry centered {% if loop.index is divisible by(2) %}alt{% endif %}">
            <div class="header-label">Version</div>
            <div>{{ bios.getVersion() }}</div>
            <div class="header-label">Note</div>
            <div>{{ bios.getNote() }}</div>
            <div class="header-label">File</div>
            <div>
                {% if bios.getFileName() is not null %}
                    <a class="combo" href="{{ vich_uploader_asset(bios, 'romFile') }}">
                        <img src="{{ absolute_url(asset('build/icons/dw.svg')) }}" alt="" width="16" height="16">
                        {% set fname = bios.getFileName() %}
                        <span>{{ fname|slice(0, fname|length - 27) ~ fname[fname|length - 4 :] }}</span>
                    </a>
                {% endif %}
            </div>
            <div class="header-label">Logs</div>
            <div>
                <a href="{{ path('dh_auditor_show_entity_history', { 'entity': audit_entity, 'id': bios.getId() }) }}">
                    <img src="{{ absolute_url(asset('build/icons/calendar.svg')) }}" alt="pwr" width="16" height="16">
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endif %}

templates/macros/buttons.html.twig
{% if type == "add" %}
    <a id="{{action}}-add-id" class="button-widget-new" data-action="click->collection#expandButton" onclick="expand('{{action}}-fields-list')">
        <span data-list-id="{{action}}-fields-list"><i class="fa fa-plus pr-1"></i> Add a new item</span>
    </a>
{% endif %}
{% if type == "del" %}
    <a style='min-width:2.5em;' class='button-widget' onclick='remove(this)'>
        <img src='{{ absolute_url(asset('build/icons/delete.svg')) }}' alt='' width='16'>
        <span>Del</span>
    </a>
{% endif %}

templates/macros/docs.html.twig
<div class="show-downloads-group last">
    {% if entity is not empty %}
        <div class="show-downloads-group-header">
            <img src="{{ absolute_url(asset('build/icons/manual.svg')) }}" alt="doc" width="32" height="32">
            <span>{{ entity|length }} {{ entity_label }} document{% if entity|length != 1 %}s{% endif %} available</span>
        </div>
        {% if entity is not empty %}
        <div class="plain-list w300p table">
            <div class="list-entry centered head">
                <div>Release date</div>
                <div>File</div>
                <div>Logs</div>
            </div>
            {% for manual in entity|sort((a, b) => a.getLinkName <=> b.getLinkName) %}
            <div class="list-entry centered {% if loop.index is divisible by(2) %}alt{% endif %}">
                <div class="header-label">Release date</div>
                <div class="perk-date-simple">{{ manual.getReleaseDateString()}}</div>
                <div class="header-label">File</div>
                <div>
                    <a class="combo" href="{{ vich_uploader_asset(manual, 'manualFile') }}">
                        <img src="{{ absolute_url(asset('build/icons/dw.svg')) }}" alt="" width="16" height="16">
                        <span>{{ manual.getLinkName() }}</span>
                    </a>
                </div>
                <div class="header-label">Logs</div>
                <div>
                    <a href="{{ path('dh_auditor_show_entity_history', { 'entity': audit_entity, 'id': manual.getId() }) }}">
                        <img src="{{ absolute_url(asset('build/icons/calendar.svg')) }}" alt="pwr" width="16" height="16">
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    {% else %}
        <div class="show-downloads-group-header last">
            <img src="{{ absolute_url(asset('build/icons/manual.svg')) }}" alt="doc" width="32" height="32">
            <span>No {{ entity_label }} documents available</span>
        </div>
    {% endif %}

    {% if chips is defined and chips is not empty %}
        {% include 'macros/docsextra.html.twig' with {'entity': chips, 'entity_label':'chip', 'reference_label':'Chip', 'icon':'chip_manual', 'audit_entity':'App-Entity-ChipDocumentation'} %}
    {% endif %}
    {% if families is defined and families is not empty %}
        {% include 'macros/docsextra.html.twig' with {'entity': families, 'entity_label':'chip family', 'reference_label':'Family', 'icon':'486', 'audit_entity':'App-Entity-EntityDocumentation'} %}
    {% endif %}
    {% if sockets is defined and sockets is not empty %}
        {% include 'macros/docsextra.html.twig' with {'entity': sockets, 'entity_label':'socket', 'reference_label':'Socket', 'icon':'cpupins', 'audit_entity':'App-Entity-EntityDocumentation'} %}
    {% endif %}
</div>

templates/macros/docsextra.html.twig
<div class="dropdown-trw">
    <label class="dropdown-header" onclick="expandDropdown(this)">
        <img src="{{ absolute_url(asset('build/icons/' ~ icon ~ '.svg')) }}" alt="alt" width="24" height="24">
        <span>{{ entity|length }} {{ entity_label }} document{% if entity|length != 1 %}s{% endif %} available</span>
        <input class="dropdown" type="checkbox" />
    </label>
    <div class="dropdown-contents">
        {% if entity is not empty %}
        <div class="plain-list w300p table">
            <div class="list-entry centered head">
                {% if reference_label is defined %}<div>{{ reference_label }}</div>{% endif %}
                <div>Release date</div>
                <div>File</div>
                <div>Logs</div>
            </div>
            {% for manual in entity|sort((a, b) => a.getLinkName <=> b.getLinkName) %}
            <div class="list-entry centered {% if loop.index is divisible by(2) %}alt{% endif %}">
                {% if reference_label is defined %}
                    <div class="header-label">{{ reference_label }}</div>
                    <div>
                        {% if reference_label == "Family" %}<a href="{{ path('family_show', {'id': manual.getProcessorPlatformType().getId()}) }}">{{ manual.getProcessorPlatformType().getName()}}</a>{% endif %}
                        {% if reference_label == "Chip" %}<a href="{{ path('chip_show', {'id': manual.getChip().getId()}) }}">{{ manual.getChip().getFullName()}}</a>{% endif %}
                        {% if reference_label == "Socket" %}<a href="{{ path('socket_show', {'id': manual.getCpuSocket().getId()}) }}">{{ manual.getCpuSocket().getNameAndType()}}</a>{% endif %}
                    </div>
                {% endif %}
                <div class="header-label">Release date</div>
                <div class="perk-date-simple">{{ manual.getReleaseDateString()}}</div>
                <div class="header-label">File</div>
                <div>
                    <a class="combo" href="{{ vich_uploader_asset(manual, 'manualFile') }}">
                        <img src="{{ absolute_url(asset('build/icons/dw.svg')) }}" alt="" width="16" height="16">
                        <span>{{ manual.getLinkName() }}</span>
                    </a>
                </div>
                <div class="header-label">Logs</div>
                <div>
                    <a href="{{ path('dh_auditor_show_entity_history', { 'entity': audit_entity, 'id': manual.getId() }) }}">
                        <img src="{{ absolute_url(asset('build/icons/calendar.svg')) }}" alt="pwr" width="16" height="16">
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</div>

templates/macros/drivers.html.twig
{% macro driver(entity) %}
    <div class="plain-list w300p table">
        <div class="list-entry centered head">
            <div>Name</div>
            <div>Version</div>
            <div>OS support</div>
            <div>Size</div>
            <div>Filename</div>
        </div>
        {% for driver in entity %}
        <div class="list-entry centered {% if loop.index is divisible by(2) %}alt{% endif %}">
            <div class="header-label">Name</div>
            <div><a href="{{ path("driver_show", {id: driver.largeFile.getId()}) }}">{{driver.largeFile.getName()}}</a></div>
            <div class="header-label">Version</div>
            <div>{{ driver.largeFile.getFileVersion() ? driver.largeFile.getFileVersion() : "<span class='badge badge-secondary'>Empty</span>" }}</div>
            <div class="header-label">OS support</div>
            <div>
                <div class="tag-container">
                {% for os in driver.largeFile.getOsFlags()|sort((a, b) => a.getName <=> b.getName)|sort((a, b) => a.getSort <=> b.getSort) %}
                <span class="text-block">
                    <img src="{{ vich_uploader_asset(os, 'icon')}}" width="16">
                    <span>{{os.getName()}}</span>
                </span>
                {% endfor %}
                {% if driver.largeFile.getOsFlags() is empty %}<span class='badge badge-secondary'>Empty</span>{% endif %}
                </div>
            </div>
            <div class="header-label">Size</div>
            <div>{{driver.largeFile.getSize() ? driver.largeFile.getSizeFormatted() : "<span class='badge badge-secondary'>Empty</span>" }}</div>
            <div class="header-label">Filename</div>
            <div>
                <a class="combo" href="{{ vich_uploader_asset(driver.largeFile, 'file')}}">
                    <img src="{{ absolute_url(asset('build/icons/dw.svg')) }}" alt="" width="16">
                    <span>{{ driver.largeFile.getFileNameSimple() }}</span>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
{% endmacro %}
<div class="show-downloads-group {{css}}">
    {% if entity is not empty %}
        {% set total = entity|length %}
        {% set recommended = entity|filter(a => a.isRecommended == true)|length %}
        {% set otherDrivers = entity|filter(a => a.isRecommended == false)|length %}
        {% if (recommended == 0 and otherDrivers == total) or (otherDrivers == 0 and recommended == total) %}
            <!-- contains only one type, show as is -->
            <div class="show-downloads-group-header">
                <img src="{{ absolute_url(asset('build/icons/hardware.svg')) }}" alt="drv" width="32" height="32">
                <span>{{ total }} driver{% if total != 1 %}s{% endif %} available</span>
            </div>
            {{ _self.driver(entity)}}
        {% else %}
            <!-- contains both recommended and not recommended -->
            <div class="show-downloads-group-header">
                <img src="{{ absolute_url(asset('build/icons/hardware.svg')) }}" alt="drv" width="32" height="32">
                <span>{{ recommended }} known good driver{% if recommended != 1 %}s{% endif %} available</span>
            </div>
            {{ _self.driver(entity|filter(a => a.isRecommended == true))}}
            <div class="dropdown-trw">
                <label class="dropdown-header" onclick="expandDropdown(this)">
                    <img src="{{ absolute_url(asset('build/icons/hardware.svg')) }}" alt="chip" width="24" height="24">
                    <span><i>{{ otherDrivers }} other driver{% if otherDrivers != 1 %}s{% endif %} available (click to expand)</i></span>
                    <input class="dropdown" type="checkbox" />
                </label>
                <div class="dropdown-contents">
                    {{ _self.driver(entity|filter(a => a.isRecommended == false))}}
                </div>
            </div>
        {% endif %}
    {% else %}
        <div class="show-downloads-group-header">
            <img src="{{ absolute_url(asset('build/icons/hardware.svg')) }}" alt="drv" width="32" height="32">
            <span>No drivers available</span>
        </div>
    {% endif %}
</div>

templates/macros/images.html.twig
<div class="show-image">
	<a href="{{ vich_uploader_asset(image, 'imageFile')}}" class="glightbox" data-description="
	{% if type == "chipset" %}
		{{ chip.getFullName() }}
	{% endif %}
	{% if image.creditor %}
		<div style='float:right;color:black;'>
			<div>
			{% if image.creditor.website %}
				<a class=creditor-href href={{ image.creditor.website }}>Image by {{image.creditor.name}}</a>
			{% else %}Image by {{ image.creditor.name }}{% endif %}
			</div>
		</div>
		<div>
			{% if image.creditor.license %}
				<a class=license-href href={{ image.creditor.license.website }}> {{ image.creditor.license.name }}</a>
			{% endif %}
		</div>
	{% endif %}
	{% if image.description %}
		<p style='color:black;'>Notes: {{ image.description }}</p>
	{% endif %}">
		<img src="{% if vich_uploader_asset(image, 'imageFile') | ext != "svg" %}{{ vich_uploader_asset(image, 'imageFile') | imagine_filter('show_thumb') }}{% else %}{{ vich_uploader_asset(image, 'imageFile')}}{% endif %}"
		width="640" height="480" alt="image{{index}}" title="{% if image.description %}{{ image.description }}{% endif %}">
		Image {{ index }} of {{ length }} {{ image.creditor ? '(' ~ image.creditor.name ~ ')'}}
	</a>
</div>

templates/macros/miscfiles.html.twig
{% if entity is not empty %}
<div class="show-downloads-group last top-border">
    <div class="show-downloads-group-header">
        <img src="{{ absolute_url(asset('build/icons/miscfile.svg')) }}" alt="doc" width="32" height="32">
        <span>{{ entity.count() }} other file{% if entity.count() != 1 %}s{% endif %} available</span>
    </div>
    <div class="plain-list w300p table">
        <div class="list-entry centered head">
            <div>Title</div>
            <div>File</div>
            <div>Logs</div>
        </div>
        {% for miscfile in entity|sort((a, b) => a.getLinkName <=> b.getLinkName) %}
        <div class="list-entry centered {% if loop.index is divisible by(2) %}alt{% endif %}">
            <div class="header-label">Title</div>
            <div>{{ miscfile.getLinkName() }}</div>
            <div class="header-label">File</div>
            <div>
                <a class="combo" href="{{ vich_uploader_asset(miscfile, 'miscFile') }}">
                    <img src="{{ absolute_url(asset('build/icons/dw.svg')) }}" alt="" width="16" height="16">
                    <span>{{ miscfile.getFileNameSimple() }}</span>
                </a>
            </div>
            <div class="header-label">Logs</div>
            <div>
                <a href="{{ path('dh_auditor_show_entity_history', { 'entity': audit_entity, 'id': miscfile.getId() }) }}">
                    <img src="{{ absolute_url(asset('build/icons/calendar.svg')) }}" alt="pwr" width="16" height="16">
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endif %}

templates/macros/navbar.html.twig
{% apply spaceless %}
<div class="show-nav" id="sh-nav">
    {% if types is not empty %}
        <input type="radio" name="tabs" id="tab-nav-1" data-tab="sh-general" checked>
        <label for="tab-nav-1"><img src="{{ absolute_url(asset('build/icons/data.svg')) }}" alt="" width="24" height="24">Description</label>
    {% endif %}
    {% if "chips" in types %}
        <input type="radio" name="tabs" id="tab-nav-2" data-tab="sh-chips">
        <label for="tab-nav-2"><img src="{{ absolute_url(asset('build/icons/chip.svg')) }}" alt="" width="24" height="24">Chips</label>
    {% endif %}
    {% if "chipspecs" in types %}
        <input type="radio" name="tabs" id="tab-nav-2" data-tab="sh-chips">
        <label for="tab-nav-2"><img src="{{ absolute_url(asset('build/icons/chip.svg')) }}" alt="" width="24" height="24">Chips/specs</label>
    {% endif %}
    {% if "specs" in types %}
        <input type="radio" name="tabs" id="tab-nav-2" data-tab="sh-specs">
        <label for="tab-nav-2"><img src="{{ absolute_url(asset('build/icons/tag.svg')) }}" alt="" width="24" height="24">Specs</label>
    {% endif %}
    {% if "bios" in types %}
        <input type="radio" name="tabs" id="tab-nav-3" data-tab="sh-bios">
        <label for="tab-nav-3"><img src="{{ absolute_url(asset('build/icons/awchip.svg')) }}" alt="" width="24" height="24">BIOS</label>
    {% endif %}
    {% if "associations" in types %}
        <input type="radio" name="tabs" id="tab-nav-3" data-tab="sh-chips">
        <label for="tab-nav-3"><img src="{{ absolute_url(asset('build/icons/chip.svg')) }}" alt="" width="24" height="24">Associations</label>
    {% endif %}
    {% if "drivers" in types %}
        <input type="radio" name="tabs" id="tab-nav-4" data-tab="sh-driver">
        <label for="tab-nav-4"><img src="{{ absolute_url(asset('build/icons/hardware.svg')) }}" alt="" width="24" height="24">Drivers</label>
    {% endif %}
    {% if "docs" in types %}
        <input type="radio" name="tabs" id="tab-nav-5" data-tab="sh-docs">
        <label for="tab-nav-5"><img src="{{ absolute_url(asset('build/icons/manual.svg')) }}" alt="" width="24" height="24">Documentation</label>
    {% endif %}
    <input type="radio" name="tabsh" id="tab-nav-h" data-URL="{{ path('dh_auditor_show_entity_history', {id:entity.getId(), entity:'App-Entity-' ~ entityName}) }}">
    <label for="tab-nav-h"><img src="{{ absolute_url(asset('build/icons/calendar.svg')) }}" alt="" width="24" height="24">Logs</label>
    {% if is_granted(role) %}
        <input type="radio" name="tabs0" id="tab-nav-0" data-URL="{{ ea_url().setDashboard('App\\Controller\\Admin\\DashboardController')
            .setController('App\\Controller\\Admin\\' ~ entityName ~ 'CrudController')
            .setAction('edit').setEntityId(entity.getId())}}">
        <label for="tab-nav-0"><img src="{{ absolute_url(asset('build/icons/edit.svg')) }}" alt="" width="24" height="24">Edit {{name}}</label>
    {% endif %}
</div>
{% endapply %}

templates/macros/player.html.twig
<div>
    <audio id="player{{index}}" src="{{src}}"></audio>
    <div class="audio-player">
        <div id="timeline{{index}}" class="timeline">
            <div id="progress{{index}}" class="progress"></div>
        </div>
        <div class="controls">
            <div class="play-container">
                <div id="toggle-play{{index}}" class="toggle-play play"></div>
            </div>
            <div class="time">
                <div id="time-current{{index}}" class="current">0:00</div>
            </div>
            <div class="volume-container">
                <div class="volume-icon">VOL</div>
                <input id="volume-slider{{index}}" class="volume-slider" type="range">
            </div>
        </div>
    </div>
</div>